leave_configs = {
    'none': [],
    'french_default': [
        {
            "code": "PN",
            "desc": "Présence de nuit",
            "kind": "presence",
            "color": "indigo",
            "position": 0,
            "visible": False,
        },
        {
            "code": "P",
            "desc": "Présent de jour",
            "kind": "presence",
            "color": "green",
            "position": 1,
            "visible": False,
        },
        {
            "code": "CN",
            "desc": "Congés normaux",
            "kind": "normal_leave",
            "color": "red",
            "position": 2,
            "visible": True,
        },
        {
            "code": "JC",
            "desc": "Jours de crédit",
            "kind": "credit_day",
            "color": "pink",
            "position": 3,
            "visible": True,
        },
        {
            "code": "CV",
            "desc": "Congés variables",
            "kind": "variable_leave",
            "color": "yellow",
            "position": 4,
            "visible": True,
        },
        {
            "code": "CH",
            "desc": "Compensations hebdomadaires",
            "kind": "saturday",
            "color": "light-blue",
            "position": 5,
            "visible": True,
        },
        {
            "code": "RH",
            "desc": "Repos hebdomadaires",
            "kind": "sunday",
            "color": "orange",
            "position": 6,
            "visible": True,
        },
        {
            "code": "RR",
            "desc": "Jours fériés",
            "kind": "holiday",
            "color": "deep-orange",
            "position": 7,
            "visible": True,
        },
        {
            "code": "HS",
            "desc": "Heures supplémentaires",
            "kind": "hour",
            "color": "teal",
            "position": 8,
            "visible": True,
        },
        {
            "code": "MM",
            "desc": "Jours de maladie",
            "kind": "counter_sick",
            "color": "red",
            "position": 9,
            "visible": False,
        },
        {
            "code": "CC",
            "desc": "Congés de circonstance",
            "kind": "counter_special",
            "color": "red",
            "position": 10,
            "visible": False,
        },
        {
            "code": "AI",
            "desc": "Absences injustifiées",
            "kind": "counter_unjustified",
            "color": "red",
            "position": 11,
            "visible": False,
        },
        {
            "code": "AG",
            "desc": "Agent en grève",
            "kind": "counter_strike",
            "color": "red",
            "position": 12,
            "visible": False,
        },
        {
            "code": "BT",
            "desc": "Agent blessé",
            "kind": "counter_wounded",
            "color": "red",
            "position": 13,
            "visible": False,
        },
        {
            "code": "OZ",
            "desc": "Récupération",
            "kind": "recovery",
            "color": "red",
            "position": 14,
            "visible": False,
        },
        {
            "code": "AP",
            "desc": "Temps partiel",
            "kind": "ignore",
            "color": "blue-grey",
            "position": 15,
            "visible": False,
        }
    ],
    'dutch_default': [
        {
            "code": "P",
            "desc": "Présent de jour",
            "kind": "presence",
            "color": "green",
            "position": 0,
            "visible": False,
        },
        {
            "code": "PN",
            "desc": "Présence de nuit",
            "kind": "presence",
            "color": "indigo",
            "position": 1,
            "visible": False,
        },
        {
            "code": "VV",
            "desc": "Congés normaux",
            "kind": "normal_leave",
            "color": "red",
            "position": 2,
            "visible": True,
        },
        {
            "code": "JC",
            "desc": "Jours de crédit",
            "kind": "credit_day",
            "color": "pink",
            "position": 3,
            "visible": True,
        },
        {
            "code": "CV",
            "desc": "Congés variables",
            "kind": "variable_leave",
            "color": "yellow",
            "position": 4,
            "visible": True,
        },
        {
            "code": "CH",
            "desc": "Compensations hebdomadaires",
            "kind": "saturday",
            "color": "light-blue",
            "position": 5,
            "visible": True,
        },
        {
            "code": "RH",
            "desc": "Repos hebdomadaires",
            "kind": "sunday",
            "color": "orange",
            "position": 6,
            "visible": True,
        },
        {
            "code": "RR",
            "desc": "Jours fériés",
            "kind": "holiday",
            "color": "deep-orange",
            "position": 7,
            "visible": True,
        },
        {
            "code": "HS",
            "desc": "Heures supplémentaires",
            "kind": "hour",
            "color": "teal",
            "position": 8,
            "visible": True,
        },
        {
            "code": "MM",
            "desc": "Jours de maladie",
            "kind": "counter_sick",
            "color": "red",
            "position": 9,
            "visible": False,
        },
        {
            "code": "CC",
            "desc": "Congés de circonstance",
            "kind": "counter_special",
            "color": "red",
            "position": 10,
            "visible": False,
        },
        {
            "code": "AI",
            "desc": "Absences injustifiées",
            "kind": "counter_unjustified",
            "color": "red",
            "position": 11,
            "visible": False,
        },
        {
            "code": "AG",
            "desc": "Agent en grève",
            "kind": "counter_strike",
            "color": "red",
            "position": 12,
            "visible": False,
        },
        {
            "code": "BT",
            "desc": "Agent blessé",
            "kind": "counter_wounded",
            "color": "red",
            "position": 13,
            "visible": False,
        },
        {
            "code": "OZ",
            "desc": "Récupération",
            "kind": "recovery",
            "color": "red",
            "position": 14,
            "visible": False,
        },
        {
            "code": "AP",
            "desc": "Temps partiel",
            "kind": "ignore",
            "color": "blue-grey",
            "position": 15,
            "visible": False,
        }
    ],
}