radium_default_config = [
    {
        "name": "shifts",
        "position": 0,
        "width": 200,
        "textsize": 15,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "description",
        "position": 1,
        "width": 400,
        "textsize": 15,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "note",
        "position": 2,
        "width": 150,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "ilt",
        "position": 3,
        "width": 80,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "files",
        "position": 4,
        "width": 260,
        "textsize": 13,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "upm",
        "position": 5,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "colt",
        "position": 6,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": True,
        "path": "https://colt-website.infrabel.be/coupure/",
    },
    {
        "name": "status",
        "position": 7,
        "width": 150,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "limits",
        "position": 8,
        "width": 600,
        "textsize": 12,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "s460s",
        "position": 9,
        "width": 300,
        "textsize": 12,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "zkl",
        "position": 10,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "cascat",
        "position": 11,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "grue",
        "position": 12,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "osv",
        "position": 13,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "loco",
        "position": 14,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "hgs",
        "position": 15,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "soudure",
        "position": 16,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "pn",
        "position": 17,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "art",
        "position": 18,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "s428",
        "position": 19,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "s461",
        "position": 20,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "atwtx",
        "position": 21,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "imputation",
        "position": 22,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "line",
        "position": 23,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "supervisor",
        "position": 24,
        "width": 150,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "extra",
        "position": 25,
        "width": 200,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },



    {
        "name": "principle",
        "position": 26,
        "width": 180,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "ctl_zx",
        "position": 27,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "prodigis",
        "position": 28,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "upm_detail",
        "position": 29,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "riparian",
        "position": 30,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "massification_date",
        "position": 31,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },



    {
        "name": "service_m",
        "position": 32,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "other_vehicle_m",
        "position": 33,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "wielding_alu_m",
        "position": 34,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "wielding_ai_m",
        "position": 35,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "atwtx_m",
        "position": 36,
        "width": 280,
        "textsize": 12,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "mhs_hour_m",
        "position": 37,
        "width": 280,
        "textsize": 12,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "pva_m",
        "position": 38,
        "width": 330,
        "textsize": 12,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "supervisor_m",
        "position": 39,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "change_request_m",
        "position": 40,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "mht_m",
        "position": 41,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "circulation_m",
        "position": 42,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "description_m",
        "position": 43,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "note_m",
        "position": 44,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "ilt_m",
        "position": 45,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "upm_m",
        "position": 46,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "colt_m",
        "position": 47,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "cascat_m",
        "position": 48,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "grue_m",
        "position": 49,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "osv_m",
        "position": 50,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "loco_m",
        "position": 51,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "hgs_m",
        "position": 52,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "extra_m",
        "position": 53,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },








    {
        "name": "printable_shifts",
        "position": 0,
        "width": 200,
        "textsize": 13,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_description",
        "position": 1,
        "width": 300,
        "textsize": 15,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_note",
        "position": 2,
        "width": 150,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_ilt",
        "position": 3,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_upm",
        "position": 4,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_colt",
        "position": 5,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_status",
        "position": 6,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_limits",
        "position": 7,
        "width": 600,
        "textsize": 12,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_s460s",
        "position": 8,
        "width": 250,
        "textsize": 12,
        "visible": True,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_zkl",
        "position": 9,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_cascat",
        "position": 10,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_grue",
        "position": 11,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_osv",
        "position": 12,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_loco",
        "position": 13,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_hgs",
        "position": 14,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_soudure",
        "position": 15,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_pn",
        "position": 16,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_art",
        "position": 17,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_s428",
        "position": 18,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_s461",
        "position": 19,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_atwtx",
        "position": 20,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_imputation",
        "position": 21,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_extra",
        "position": 22,
        "width": 200,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_line",
        "position": 23,
        "width": 100,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_supervisor",
        "position": 24,
        "width": 150,
        "textsize": 13,
        "visible": True,
        "multiple": False,
        "clickable": False,
        "path": None,
    },




    {
        "name": "printable_principle",
        "position": 26,
        "width": 180,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_ctl_zx",
        "position": 27,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_prodigis",
        "position": 28,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_upm_detail",
        "position": 29,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_riparian",
        "position": 30,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_massification_date",
        "position": 31,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": False,
        "clickable": False,
        "path": None,
    },



    {
        "name": "printable_service_m",
        "position": 32,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_other_vehicle_m",
        "position": 33,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_wielding_alu_m",
        "position": 34,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_wielding_ai_m",
        "position": 35,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_atwtx_m",
        "position": 36,
        "width": 280,
        "textsize": 12,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_mhs_hour_m",
        "position": 37,
        "width": 280,
        "textsize": 12,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_pva_m",
        "position": 38,
        "width": 330,
        "textsize": 12,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_supervisor_m",
        "position": 39,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_change_request_m",
        "position": 40,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_mht_m",
        "position": 41,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_circulation_m",
        "position": 42,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_description_m",
        "position": 43,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_note_m",
        "position": 44,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_ilt_m",
        "position": 45,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_upm_m",
        "position": 46,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_colt_m",
        "position": 47,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_cascat_m",
        "position": 48,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_grue_m",
        "position": 49,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_osv_m",
        "position": 50,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_loco_m",
        "position": 51,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_hgs_m",
        "position": 52,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },
    {
        "name": "printable_extra_m",
        "position": 53,
        "width": 150,
        "textsize": 13,
        "visible": False,
        "multiple": True,
        "clickable": False,
        "path": None,
    },


]
