[
    {
        "code": "P",
        "desc": "Présent de jour",
        "kind": "presence",
        "color": "green",
        "position": 0,
        "visible": false,
    },
    {
        "code": "PN",
        "desc": "Présence de nuit",
        "kind": "presence",
        "color": "indigo",
        "position": 1,
        "visible": false,
    },
    {
        "code": "CN",
        "desc": "Congés normaux",
        "kind": "normal_leave",
        "color": "red",
        "position": 2,
        "visible": true,
    },
    {
        "code": "JC",
        "desc": "Jours de crédit",
        "kind": "credit_day",
        "color": "pink",
        "position": 3,
        "visible": true,
    },
    {
        "code": "CV",
        "desc": "Congés variables",
        "kind": "variable_leave",
        "color": "yellow",
        "position": 4,
        "visible": true,
    },
    {
        "code": "CH",
        "desc": "Compensations hebdomadaires",
        "kind": "saturday",
        "color": "light-blue",
        "position": 5,
        "visible": true,
    },
    {
        "code": "RH",
        "desc": "Repos hebdomadaires",
        "kind": "sunday",
        "color": "orange",
        "position": 6,
        "visible": true,
    },
    {
        "code": "RR",
        "desc": "Jours fériés",
        "kind": "holiday",
        "color": "deep-orange",
        "position": 7,
        "visible": true,
    },
    {
        "code": "HS",
        "desc": "Heures supplémentaires",
        "kind": "hour",
        "color": "teal",
        "position": 8,
        "visible": true,
    },
    {
        "code": "MM",
        "desc": "Jours de maladie",
        "kind": "counter_sick",
        "color": "red",
        "position": 9,
        "visible": false,
    },
    {
        "code": "CC",
        "desc": "Congés de circonstance",
        "kind": "counter_special",
        "color": "red",
        "position": 10,
        "visible": false,
    },
    {
        "code": "AI",
        "desc": "Absences injustifiées",
        "kind": "counter_unjustified",
        "color": "red",
        "position": 11,
        "visible": false,
    },
    {
        "code": "AG",
        "desc": "Agent en grève",
        "kind": "counter_strike",
        "color": "red",
        "position": 12,
        "visible": false,
    },
    {
        "code": "BT",
        "desc": "Agent blessé",
        "kind": "counter_wounded",
        "color": "red",
        "position": 13,
        "visible": false,
    },
    {
        "code": "OZ",
        "desc": "Récupération",
        "kind": "recovery",
        "color": "red",
        "position": 14,
        "visible": false,
    },
    {
        "code": "AP",
        "desc": "",
        "kind": "ignore",
        "color": "blue-grey",
        "position": 15,
        "visible": false,
    }
]