radium_default_config = [
    {
        'name': 'shifts',
        'position': 0,
        'width': 200,
        'textsize': 15,
        'visible': True,
    },
    {
        'name': 'description',
        'position': 1,
        'width': 400,
        'textsize': 15,
        'visible': True,
    },
    {
        'name': 'note',
        'position': 2,
        'width': 150,
        'textsize': 15,
        'visible': True,
    },
    {
        'name': 'ilt',
        'position': 3,
        'width': 80,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'files',
        'position': 4,
        'width': 200,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'upm',
        'position': 5,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'colt',
        'position': 6,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'status',
        'position': 7,
        'width': 150,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'limits',
        'position': 8,
        'width': 600,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 's460s',
        'position': 9,
        'width': 300,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'zkl',
        'position': 10,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'cascat',
        'position': 11,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'grue',
        'position': 12,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'osv',
        'position': 13,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'loco',
        'position': 14,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'hgs',
        'position': 15,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'soudure',
        'position': 16,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'pn',
        'position': 17,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'art',
        'position': 18,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 's428',
        'position': 19,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 's461',
        'position': 20,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'atwtx',
        'position': 21,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'imputation',
        'position': 22,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'extra',
        'position': 23,
        'width': 200,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'line',
        'position': 24,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'supervisor',
        'position': 25,
        'width': 150,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_shifts',
        'position': 0,
        'width': 200,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_description',
        'position': 1,
        'width': 300,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_note',
        'position': 2,
        'width': 200,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_ilt',
        'position': 3,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_upm',
        'position': 5,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_colt',
        'position': 6,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_status',
        'position': 7,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_limits',
        'position': 8,
        'width': 600,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_s460s',
        'position': 9,
        'width': 300,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_zkl',
        'position': 10,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_cascat',
        'position': 11,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_grue',
        'position': 12,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_osv',
        'position': 13,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_loco',
        'position': 14,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_hgs',
        'position': 15,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_soudure',
        'position': 16,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_pn',
        'position': 17,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_art',
        'position': 18,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_s428',
        'position': 19,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_s461',
        'position': 20,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_atwtx',
        'position': 21,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_imputation',
        'position': 22,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_extra',
        'position': 23,
        'width': 200,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_line',
        'position': 24,
        'width': 100,
        'textsize': 13,
        'visible': True,
    },
    {
        'name': 'printable_supervisor',
        'position': 25,
        'width': 150,
        'textsize': 13,
        'visible': True,
    }
]