from .all_profiles import AllProfilesView
from .apps import AppsView
from .board import BoardView
from .calendar import CalendarView
from .calls import CallsView
from .cell import CellView
from .contacts import ContactsView
from .day import DayView
from .element import ElementView
from .home import HomeView
from .leave import LeaveView
from .logs import LogsView
from .messages import MessagesView
from .my_apex import MyApexView
from .my_apex_projects import MyApexProjectsView
from .presences import PresencesView
from .profile import ProfileView
from .project import ProjectView
from .projects import ProjectsView
from .quota import QuotaView
from .quota_light import QuotaLightView
from .reset_password import ResetPasswordView
from .shifts import ShiftsView
from .team import TeamView
from .templates import TemplatesView
from .works import WorksView
from .worksmobile import WorksMobileView