# Generated by Django 3.2.3 on 2021-05-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppWorkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_appworklink_apps', to='apex.app')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.CharField(blank=True, max_length=20, null=True)),
                ('absence', models.CharField(blank=True, max_length=20, null=True)),
                ('short', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('has_content', models.BooleanField(default=False)),
                ('has_call', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('has_content', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.app')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('heading', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.app')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('ident', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apex_profile_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.app')),
            ],
        ),
        migrations.CreateModel(
            name='RR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.circle')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('ilt', models.TextField(blank=True, null=True)),
                ('upm', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('zkl', models.TextField(blank=True, null=True)),
                ('cascat', models.TextField(blank=True, null=True)),
                ('grue', models.TextField(blank=True, null=True)),
                ('osv', models.TextField(blank=True, null=True)),
                ('loco', models.TextField(blank=True, null=True)),
                ('hgs', models.TextField(blank=True, null=True)),
                ('soudure', models.TextField(blank=True, null=True)),
                ('pn', models.TextField(blank=True, null=True)),
                ('art', models.TextField(blank=True, null=True)),
                ('s428', models.TextField(blank=True, null=True)),
                ('s461', models.TextField(blank=True, null=True)),
                ('atwtx', models.TextField(blank=True, null=True)),
                ('imputation', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('scst', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('apps', models.ManyToManyField(blank=True, related_name='apex_work_works', through='apex.AppWorkLink', to='apex.App')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_workfilelink_files', to='apex.file')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_workfilelink_works', to='apex.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='apex_work_works', through='apex.WorkFileLink', to='apex.File'),
        ),
        migrations.CreateModel(
            name='TeamProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('is_editor', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_printable', models.BooleanField(default=True)),
                ('can_see_private', models.BooleanField(default=False)),
                ('can_see_cells', models.BooleanField(default=False)),
                ('can_see_quotas', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_teamprofilelink_profiles', to='apex.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_teamprofilelink_teams', to='apex.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='apex_team_circles', through='apex.TeamProfileLink', to='apex.Profile'),
        ),
        migrations.CreateModel(
            name='TaskSubtaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_tasksubtasklink_subtasks', to='apex.subtask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_tasksubtasklink_tasks', to='apex.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_tasknotelink_notes', to='apex.note')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_tasknotelink_tasks', to='apex.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_taskfilelink_files', to='apex.file')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_taskfilelink_tasks', to='apex.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFieldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_taskfieldlink_fields', to='apex.field')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_taskfieldlink_tasks', to='apex.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='apex_task_tasks', through='apex.TaskFieldLink', to='apex.Field'),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='apex_task_tasks', through='apex.TaskFileLink', to='apex.File'),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='apex_task_tasks', through='apex.TaskNoteLink', to='apex.Note'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='apex_task_tasks', through='apex.TaskSubtaskLink', to='apex.Subtask'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(blank=True, max_length=100, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.work')),
            ],
        ),
        migrations.CreateModel(
            name='S460',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.CharField(blank=True, max_length=100, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.work')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_projecttasklink_projects', to='apex.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_projecttasklink_tasks', to='apex.task')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='apex_project_projects', through='apex.ProjectTaskLink', to='apex.Task'),
        ),
        migrations.CreateModel(
            name='PartProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participant', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_partprofilelink_parts', to='apex.part')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_partprofilelink_profiles', to='apex.profile')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='apex_part_parts', through='apex.PartProfileLink', to='apex.Profile'),
        ),
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apex.project'),
        ),
        migrations.AddField(
            model_name='part',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.shift'),
        ),
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.team'),
        ),
        migrations.AddField(
            model_name='part',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.work'),
        ),
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apex.profile'),
        ),
        migrations.CreateModel(
            name='ModelFieldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_modelfieldlink_fields', to='apex.field')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_modelfieldlink_models', to='apex.model')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='apex_model_models', through='apex.ModelFieldLink', to='apex.Field'),
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_line', models.CharField(blank=True, max_length=100, null=True)),
                ('from_station', models.CharField(blank=True, max_length=100, null=True)),
                ('from_signal', models.CharField(blank=True, max_length=100, null=True)),
                ('from_lane', models.CharField(blank=True, max_length=100, null=True)),
                ('from_pk', models.CharField(blank=True, max_length=100, null=True)),
                ('to_line', models.CharField(blank=True, max_length=100, null=True)),
                ('to_station', models.CharField(blank=True, max_length=100, null=True)),
                ('to_signal', models.CharField(blank=True, max_length=100, null=True)),
                ('to_lane', models.CharField(blank=True, max_length=100, null=True)),
                ('to_pk', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.work')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('cn', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cv', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ch', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rh', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rr', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DayTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_daytasklink_days', to='apex.day')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_daytasklink_tasks', to='apex.task')),
            ],
        ),
        migrations.CreateModel(
            name='DayNoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_daynotelink_days', to='apex.day')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_daynotelink_notes', to='apex.note')),
            ],
        ),
        migrations.CreateModel(
            name='DayFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_dayfilelink_days', to='apex.day')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_dayfilelink_files', to='apex.file')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='apex_day_days', through='apex.DayFileLink', to='apex.File'),
        ),
        migrations.AddField(
            model_name='day',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='apex_day_days', through='apex.DayNoteLink', to='apex.Note'),
        ),
        migrations.AddField(
            model_name='day',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='apex_day_days', through='apex.DayTaskLink', to='apex.Task'),
        ),
        migrations.CreateModel(
            name='CellTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_celltasklink_cells', to='apex.cell')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_celltasklink_tasks', to='apex.task')),
            ],
        ),
        migrations.CreateModel(
            name='CellNoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_cellnotelink_cells', to='apex.cell')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_cellnotelink_notes', to='apex.note')),
            ],
        ),
        migrations.CreateModel(
            name='CellFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_cellfilelink_cells', to='apex.cell')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_cellfilelink_files', to='apex.file')),
            ],
        ),
        migrations.CreateModel(
            name='CellCallLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_cellcalllink_calls', to='apex.call')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_cellcalllink_cells', to='apex.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='calls',
            field=models.ManyToManyField(blank=True, related_name='apex_cell_cells', through='apex.CellCallLink', to='apex.Call'),
        ),
        migrations.AddField(
            model_name='cell',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='apex_cell_cells', through='apex.CellFileLink', to='apex.File'),
        ),
        migrations.AddField(
            model_name='cell',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='apex_cell_cells', through='apex.CellNoteLink', to='apex.Note'),
        ),
        migrations.AddField(
            model_name='cell',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.profile'),
        ),
        migrations.AddField(
            model_name='cell',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='apex_cell_cells', through='apex.CellTaskLink', to='apex.Task'),
        ),
        migrations.AddField(
            model_name='appworklink',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apex_appworklink_works', to='apex.work'),
        ),
        migrations.AddField(
            model_name='app',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apex.team'),
        ),
    ]
